all: print_last_10_lines_of_file struc_hack sum_natural_numbers series_sum1 GP_series largenumber_multiplication largenumber_devision largest_sum_contiguous_subarray palindrome add add_number 2nd_largest_number

print_last_10_lines_of_file:
	gcc print_last_10_lines_of_file.c -o print_last_10_lines_of_file

struc_hack:
	gcc struc_hack.c -o struc_hack

sum_natural_numbers:
	gcc sum_natural_numbers.c -o sum_natural_numbers

series_sum1:
	gcc series_sum1.c -o series_sum1

GP_series:
	gcc GP_series.c -o GP_series

largenumber_multiplication:
	gcc largenumber_multiplication.c -o largenumber_multiplication

largenumber_devision:
	gcc largenumber_devision.c -o largenumber_devision

largest_sum_contiguous_subarray:
	gcc largest_sum_contiguous_subarray.c -o largest_sum_contiguous_subarray

2nd_largest_number:
	gcc 2nd_largest_number.c -o 2nd_largest_number

add: 
	gcc add.c -o add

add_number:
	gcc add_number.c -o add_number

palindrome:
	gcc palindrome.c -o palindrome

clean:
	@rm -rf print_last_10_lines_of_file
	@rm -rf struc_hack 
	@rm -rf sum_natural_numbers 
	@rm -rf series_sum1 
	@rm -rf GP_series 
	@rm -rf largenumber_multiplication 
	@rm -rf largenumber_devision 
	@rm -rf largest_sum_contiguous_subarray
	@rm -rf 2nd_largest_number 
	@rm -rf add
	@rm -rf add_number
	@rm -rf palindrome
