all:
	gcc print_last_10_lines_of_file.c -o print_last_10_lines_of_file
	gcc struc_hack.c -o struc_hack
	gcc sum_natural_numbers.c -o sum_natural_numbers
	gcc series_sum1.c -o series_sum1
	gcc series_sum2.c -o series_sum2
	gcc GP_series.c -o GP_series 
	gcc largenumber_multiplication.c -o largenumber_multiplication 
	gcc largenumber_devision.c -o largenumber_devision

print_last_10_lines_of_file:
	gcc print_last_10_lines_of_file.c -o print_last_10_lines_of_file

struc_hack:
	gcc struc_hack.c -o struc_hack

sum_natural_numbers:
	gcc sum_natural_numbers.c -o sum_natural_numbers

series_sum1:
	gcc series_sum1.c -o series_sum1

series_sum2:
	gcc series_sum2.c -o series_sum2

GP_series:
	gcc GP_series.c -o GP_series

largenumber_multiplication:
	gcc largenumber_multiplication.c -o largenumber_multiplication

largenumber_devision:
	gcc largenumber_devision.c -o largenumber_devision


clean:
	@rm -rf print_last_10_lines_of_file.exe print_last_10_lines_of_file
	@rm -rf struc_hack struc_hack.exe 
	@rm -rf sum_natural_numbers sum_natural_numbers.exe
	@rm -rf series_sum1 series_sum1.exe
	@rm -rf series_sum2 series_sum2.exe
	@rm -rf GP_series GP_series.exe
	@rm -rf largenumber_multiplication largenumber_multiplication.exe
	@rm -rf largenumber_devision largenumber_devision.exe
