all:
	gcc print_last_10_lines_of_file.c -o print_last_10_lines_of_file
	gcc struc_hack.c -o struc_hack

clean:
	rm -rf print_last_10_lines_of_file.exe print_last_10_lines_of_file
	rm -rf struc_hack struc_hack.exe 
